all: fig-VGLCSex.pdf fig-interval-decomposition.pdf

fig-VGLCSex.pdf: fig-VGLCSex.tex
	xelatex fig-VGLCSex.tex

fig-interval-decomposition.pdf: fig-interval-decomposition.tex
	xelatex fig-interval-decomposition.tex

clean:
	rm -f *.aux *.log *.nav *.out *.pdf *.snm *.toc *.vrb
